logging:
  file:
    path: src/main/resources/log
  level:
    root: INFO
spring:
  jpa:
    defer-datasource-initialization: 'true'
    show-sql: 'true'
  datasource:
    password: ''
    driver-class-name: org.h2.Driver
    username: lutz
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: 'true'
mocky:
  url: https://run.mocky.io/v3/5dc16e9f-b99b-4828-9c99-774c2a066bd7
lutzapi:
  seed: 'true'
  jwt:
    expiration-time: '3600'
    secret-key: '!===123123===!'